{% set name = "pyretis" %}
{% set version = "2.2.1" %}
{% set sha256 = "9f4705bcb804802202e63a50b28f71805398f6b725e62a867ecf5c796d9bd53c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: true  # [py<36]
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv" 


requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
    - cython
    - numpy
    - zlib
    - msinttypes  # [win and py27]
  run:
    - python
    - cython
    - sphinx
    - sphinx_bootstrap_theme
    - setuptools
    - {{ pin_compatible('numpy') }}
    - scipy
    - pandas
    - pytables
    - zlib
    - colorama
    - tqdm
    - docutils
    - matplotlib
    - jinja2
    - mdtraj

test:
  imports:
    - pyretis

about:
  home: http://www.pyretis.org
  license: LGPLv2.1+
  license_file: LICENSE
  summary: 'PyRETIS: A well-done, medium-sized python library for rare events, DOI: 10.1002/jcc.24900'

extra:
  recipe-maintainers:
    - EnricoRiccardi
    - andersle
    - sroet
